### ISSUE TITLE
Database Update

### ISSUE THREAD

**Issue by bkoffler** [bitcoin-abe/bitcoin-abe#195]
I know this is a simple question but i am new to this program. After the intial database upload from the blockchain, does ABE keep the database up to date as new blocks are downloaded or do i need to manually pull those blocks in?

**Comment by dermoth** [comment]
By default the same process that serves ABE also looks for ned blocks and import the. This was OK in the early days, but now that blocks can take a while to load this will block incoming requests until all new blocks are loaded.

The recommended way to load blocks is to run abe with `--no-serve` in a separate process to load blocks, and serve the pages with `--no-load`. Since `--no-serve` exits once done you can use abe_loader in the tools directory to watch the bitcoin log and start Abe loader as needed.

A 3rd method which I added recently is to load blocks and mempool continuously using the --rpc-load-mempool option. This has the fastest block load times as transactions are loaded before the blocks as they're advertised on the network. You may want to also get my last PR #198 which allows cleaning up the unlinked transactions (without it the transaction that never make it to a block will remain in DB forever).
