### ISSUE TITLE
Database size

### ISSUE THREAD

**Issue by rsarres** [bitcoin-abe/bitcoin-abe#207]
Hi guys;
I was searching a blockchain explorer and found bitcoin-abe. After a quick read of the documentation, I downloaded and started a database blockfile load (POSTGRESQL). As I have a i7 machine with ssd drive, I thought it would take some days as the documentation warns, but it should be feasible. 
Well, almost 7 days from the initial load, I can tell you that it will take weeks more and space I do not have on SSD disks. The database load is around block 310000 and my database size is already 110GB. As the blocks at this height are only 40% full, I noticed that it will only get worse, so I stopped the load to move the database to a slower but bigger storage. I think the database size may surpass 300GB and 20 days of load time, maybe more now that I will use slower disks. At this height, my performance was around 15 blocks per minute.
I just want to left a warning sign to anyone new to bitcoin-abe.

Lastly, I have a question:
I saw a bitcoin-abe small branch that should be faster, smaller, but misses some APIs. Do you suggest using it? The missing features are important?

By the way, any suggestion to speed up the load and shrink the database would be greatly appreciated too.

**Comment by dermoth** [comment]
If you want more compact, my entire database fits in 115GB with TokuDB and default compression settings (running MariaDB 10.0 form Debian stable, MariaDB is the fork of MySQL away from Oracle). Also SQL backups and loads are much faster and I can share a script to backup TokuDB using LOAD DATA INFILE, which gives an additional performance boost with the TokuDB engine.

The InnoDB version is more like 168GB, with some of the biggest tables compressed as per `README-MYSQL.txt`: APPENDIX A -- Using InnoDB Compressed Tables. The main difference is that TokuDB do not enforce foreign keys, which can be problematic for development hence why I have also an InnoDB version.

RPC load can also slow down a lot bulk import time... I've been thinking about moving the rpc calls to a separate thread to load blocks & tx'es in parallel... even better would be adding a getrawblock command to bitcoind, which would avoid the need for txindex and save a lot of rpc calls (right now we get the block header & tx hashes, then one rpc call per tx! A single call could get the entire block as stored on disk). For fast bulk import use blkfile, the switch to rpc to import mempool between blocks and get ultra fast new block imports (since most tx'es will already be imported).

FWIW I run Bitcoind, abe on both InnoDB and TokuDB (two distinct loaders), plus development work in parallel (ex backups & reloads, rescanning the whole DB while adding checks/repairs to Abe.verify) on a software raid1 made of two cheap 2TB disks (~150$ CAD together) and I'm still able to keep my db's  current. I don't think this will last long though, especially with the upcoming block size increases.

**Comment by dermoth** [comment]
Also, one thing you can easily do with InnoDB and file_per_table is move only some of the files to SSD. Generally the ib system tablespace, doublewrite buffer and logfiles can stay on rotational disks; writes are mostly sequential and outside large rollbacks and database recovery after crash/powerfail you shouldn't suffer much from IO performance. The rest of the database, or part of it, can be moved to SSD using symlinks (while MySQL is stopped). When indexes don't fit in memory, importing data causes a lot of random reads to the tablespace to check for key collisions, plus finding and linking tx'es to previous blocks/tx and pubkeys, and SSDs perform best at this.

A couple months ago I restarted my InnoDB load after about a year of downtime (when I realized I'd need it for FK checks). I have only a 128GB SSD, probably ~60GB were free on it at that time. Using the PERFORMANCE_SCHEMA tables I could find out which tables caused the most IO wait during import and move only those tables to SSD which allowed me to save months of import time.

BTW also check your SSD's rated life percentage remaining; SSDs have limited number of writes, usually enough for most ppl, but with bitcoin running on it besides the small size one reason I moved everything away was the speed at which the SSD life was being consumed. Again system tables will get most writes (all pages written to the database will be written in the doublewrite buffer first, plus the undo and redo logs!) so leaving them on rotational disks will help...

**Comment by dermoth** [comment]
On a side note, one project I wanted to start for a while is a partial or complete rewrite of abe dropping all sequences and using block/tx hashes directly instead. This would save a lot of read IO looking up these id's and would likely save some space as well. A partial rewrite would still be quite some work considering the complexity (support for altcoins, sql abstraction...) while for a full rewrite I'd likely look at using external bitcoin apis and single database support. I didn't manage to find enough time to work seriously on either one yet...

**Comment by Callosis** [comment]
I

**Comment by rsarres** [comment]
Thank you for all the tips. Really appreciated.

**Comment by dermoth** [comment]
For the heads up, I mentioned the lack of "getrawblock" in bitcoind, as it turns out getblock defaults to verbose and turning it off allow getting full block data in a single RPC call!

Commit a974b8b1be7 in my fork does it; since we already had raw block decoding support for blockfile it was easy to implement it to the RPC loader.

The bottleneck now is back to Python, just like it was with plain blockfile import. It also remove the need for txindex=1 in bitcoind, at least without catch_up_mempool (for the latter I'll have to test.. I'm assuming at the very least we'll have to handle the case where the TX we're trying to load just made it to a block and is no longer accessible)
