### ISSUE TITLE
Is it possible to use Mongodb instead of SQL ?

### ISSUE THREAD

**Issue by albabosh** [bitcoin-abe/bitcoin-abe#259]
Is it possible to use Mongodb instead of SQL & what should be done ?

**Comment by dermoth** [comment]
If you can code it... probably best to start from scratch. The real question though is WHY?

Don't think just because you use another product it will miracally become fast - abe is slow because there are lots of data links to create and update - unless you can leverage a large cluster of nodes and parallelize work there's no way the same functionality could become much faster on MongoDB or any other NoSQL database.
