### ISSUE TITLE
Page Not Found Handler Cross-site Scripting -- CVE-2020-11944

### ISSUE THREAD

**Issue by geeknik** [bitcoin-abe/bitcoin-abe#292]
A lack of filtering around line 253 of abe.py
```
        except PageNotFound:
            page['status'] = '404 Not Found'
            page['body'] = ['<p class="error">Sorry, ', env['SCRIPT_NAME'],
                            env['PATH_INFO'],
                            ' does not exist on this server.</p>']
```
allows attackers to abuse the Page Not Found error handler and pass rogue JavaScript to unsuspecting users using a specially crafted URL:

`https://host.name/<img src=x onerror=alert(document.cookie)>">`

MITRE has assigned [CVE-2020-11944](https://nvd.nist.gov/vuln/detail/CVE-2020-11944) to this flaw. Thank you.

**Comment by Lvl4Sword** [comment]
I'm quite honestly disappointed that you didn't properly disclose this and instead chose to publicly display it in the issues for everyone to see.
There are quite a few instances of Abe currently active that are vulnerable to this.

**Comment by Lvl4Sword** [comment]
To anyone stumbling across this:
Within abe.py's ``__call__``, change
```py
"dotdot": "../" * (env['PATH_INFO'].count('/') - 1),
```
to
```py
"dotdot": "../" * (escape(env['PATH_INFO']).count('/') - 1),
```
( this is because ``escape`` is already imported from ``cgi`` )

Also, since this iteration of Abe is Python 2,
take a look at my Woodcoin Python 3 fork of Abe at
<https://github.com/woodcoin-core/woodcoin-explorer/> and use that for the time being.

I'm working on a Flask version which should be done soon* as well.

**Comment by dermoth** [comment]
Thanks for the fix @Lvl4Sword  - merged in Abe too

**Comment by Lvl4Sword** [comment]
@dermoth Actually, since 3.2 cgi.escape has been deprecated - https://docs.python.org/3.5/library/cgi.html#cgi.escape and html.escape is recommended instead with quote=True

**Comment by Lvl4Sword** [comment]
Alright, so proper fix consists of the following:
Within ``__call__``, set
```py
env['PATH_INFO'] = escape(env['PATH_INFO'], quote=True)
```
right above the ``page`` dictionary. Then within the ``page`` dictionary, set

```py
"dotdot": "../" * (env['PATH_INFO'].count('/') - 1),
```

You can verify this is the proper fix because something like
``<BODY ONLOAD=alert('XSS')>`` will actually be presented into the HTML, as opposed to hidden and trying to be executed.

**Comment by Lvl4Sword** [comment]
This has been fixed, closed.
