### ISSUE TITLE
Initial MySQL load is only using 0.5% of CPU and 45% of the Disk.

### ISSUE THREAD

**Issue by M103Tanker** [bitcoin-abe/bitcoin-abe#297]
I know other people have asked similar questions but I was curious if any new updates or solutions have come out.  My initial MySQL loaded has been going on for a long time which I understand is the norm.  My question is why is it only using 0.5% of my CPU, 120MB of my 12GB memory, and 45% of the disk.  I only have one disk installed.

**Comment by datudou** [comment]
Don't use remote myql sever. Use the local mysql server with the python -m abe in the same machine.

**Comment by dermoth** [comment]
I think the issue is more about tuning. MySQL/InnoDB needs to be told explicitly how much ram to use. If it's not using much ram, they you haven't properly runed it. That said 12G it not much, and unless you have fast NVMe/SSd disks it won't be very practical anyway (and consumer drives won't last many years under a heavy write regime...)

Running abe locally may help, only if you can still give it similar resources. A fast network/closeby server should be probably nearly as fast, it all depends on how long it take to read data (ex all cached in ram vs. slower disk access). If your server is already slow network won't make it much worse, but import will be very slow anyway.
