### ISSUE TITLE
How to convert Varbinary(65) to readable format?

### ISSUE THREAD

**Issue by mrantonion** [bitcoin-abe/bitcoin-abe#306]
Hello everyone!

Can anyone explain what to do next with varbinary column of public keys in sql file? How it's possible to convert public keys' column to readable HEX format?

Best regards.

**Comment by mrantonion** [comment]
I've found how to do it. May be someone will find it helpful.
I imported sql database to any SQL editor. Then exported column with Varbinary data to csv. Then imported in excel and converted to HEX. Evrth was simple. ))

**Comment by Lvl4Sword** [comment]
You haven't stated what database type you're using.
If it's MySQL you can use the HEX function -> https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_hex

**Comment by mrantonion** [comment]
I've found a more simple decision. (I'm using SQLite format). I loaded a sqlite file onto editor. Then exported as SQL type. And that's all! I've obtained a simple csv-file with HEX data of public keys. Great! ))

**Comment by dermoth** [comment]
That's because SQLite doesn't support binary formats. You can also disable it for MySQL and PostgreSQL - all those binary fields will take twice the space though, but they will be stored as hex.

Because of the size overhead and performance impact of converting to/from hex, it is preferable to sore as binary and only decode as needed. In SQL you can do that directly, ex with the HEX() function of MySQL/Maria.
